spring:
  cloud:
    gateway:
      routes:
        - id: service-msproducts
          uri: lb://service-msproducts
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: service-msitem
          uri: lb://service-msitem
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
        - id: service-msusers
          uri: lb://service-msusers
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: service-msauth
          uri: lb://service-msauth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2                                 